begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  team text not null default 'Diğer',
  team_changed boolean not null default false,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists team text default 'Diğer';
alter table public.profiles add column if not exists team_changed boolean not null default false;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
create unique index if not exists profiles_username_lower_uidx on public.profiles (lower(username));

create table if not exists public.matches (
  id text primary key,
  hafta integer not null check (hafta > 0),
  ev text not null,
  konuk text not null,
  kickoff timestamptz not null,
  stadyum text,
  featured boolean not null default false,
  verified boolean not null default false,
  status text,
  referee_name text,
  referee_stats jsonb,
  weather jsonb,
  source text,
  updated_at timestamptz not null default now(),
  check (ev <> konuk)
);
alter table public.matches add column if not exists stadyum text;
alter table public.matches add column if not exists featured boolean not null default false;
alter table public.matches add column if not exists verified boolean not null default false;
alter table public.matches add column if not exists status text;
alter table public.matches add column if not exists referee_name text;
alter table public.matches add column if not exists referee_stats jsonb;
alter table public.matches add column if not exists weather jsonb;
alter table public.matches add column if not exists source text;
alter table public.matches add column if not exists updated_at timestamptz not null default now();
create index if not exists matches_week_kickoff_idx on public.matches (hafta, kickoff);
create index if not exists matches_kickoff_idx on public.matches (kickoff);

create table if not exists public.match_analysis (
  match_id text primary key references public.matches(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.predictions (
  match_id text not null references public.matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  pick text not null check (pick in ('1','X','2')),
  score_home integer check (score_home between 0 and 99),
  score_away integer check (score_away between 0 and 99),
  submitted_at timestamptz not null default now(),
  primary key (match_id, user_id),
  check ((score_home is null) = (score_away is null))
);
create unique index if not exists predictions_match_user_uidx on public.predictions (match_id, user_id);
create index if not exists predictions_user_idx on public.predictions (user_id, submitted_at desc);
create index if not exists predictions_match_idx on public.predictions (match_id);

create table if not exists public.results (
  match_id text primary key references public.matches(id) on delete cascade,
  home integer not null check (home between 0 and 99),
  away integer not null check (away between 0 and 99),
  scored_at timestamptz not null default now()
);

create table if not exists public.rewards (
  team text not null,
  sira integer not null check (sira between 1 and 3),
  aciklama text not null,
  updated_at timestamptz not null default now(),
  primary key (team, sira)
);
create unique index if not exists rewards_team_rank_uidx on public.rewards (team, sira);

create table if not exists public.league_standings (
  id bigint generated by default as identity primary key,
  season text not null,
  week integer,
  team text not null,
  played integer not null default 0,
  won integer not null default 0,
  drawn integer not null default 0,
  lost integer not null default 0,
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  goal_difference integer not null default 0,
  points integer not null default 0,
  home_played integer not null default 0,
  home_points integer not null default 0,
  away_played integer not null default 0,
  away_points integer not null default 0,
  form text,
  source text,
  verified_at timestamptz,
  unique (season, week, team)
);
create index if not exists league_standings_lookup_idx on public.league_standings (season, week, points desc);

create table if not exists public.weekly_stories (
  week integer primary key check (week > 0),
  title text not null,
  intro text,
  cards jsonb not null default '[]'::jsonb,
  watch_for jsonb not null default '[]'::jsonb,
  is_published boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.match_lineups (
  id bigint generated by default as identity primary key,
  match_id text not null references public.matches(id) on delete cascade,
  team text not null,
  player_name text not null,
  position text,
  number integer,
  is_captain boolean not null default false,
  is_keeper boolean not null default false,
  is_official boolean not null default false,
  source text,
  verified_at timestamptz,
  unique (match_id, team, player_name)
);
create index if not exists match_lineups_match_idx on public.match_lineups (match_id, team);

create table if not exists public.match_absences (
  id bigint generated by default as identity primary key,
  match_id text not null references public.matches(id) on delete cascade,
  team text not null,
  player_name text not null,
  availability_status text not null,
  reason text,
  verification_status text not null default 'provider',
  source text,
  verified_at timestamptz,
  unique (match_id, team, player_name, availability_status)
);
create index if not exists match_absences_match_idx on public.match_absences (match_id, team);

create table if not exists public.model_predictions (
  match_id text primary key references public.matches(id) on delete cascade,
  home_probability numeric(6,3),
  draw_probability numeric(6,3),
  away_probability numeric(6,3),
  xg_home numeric(6,3),
  xg_away numeric(6,3),
  model_version text,
  inputs jsonb not null default '{}'::jsonb,
  calculated_at timestamptz not null default now()
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id text not null references public.matches(id) on delete cascade,
  provider_event_id text,
  minute integer check (minute between 0 and 180),
  event_type text not null,
  team text,
  player_name text,
  related_player_name text,
  detail text,
  verified boolean not null default false,
  occurred_at timestamptz,
  unique nulls not distinct (match_id, provider_event_id)
);
create index if not exists match_events_match_minute_idx on public.match_events (match_id, minute);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  candidate text;
  supported_team text;
begin
  candidate := left(coalesce(nullif(trim(new.raw_user_meta_data->>'username'), ''), split_part(new.email, '@', 1), 'taraftar'), 40);
  if exists (select 1 from public.profiles where lower(username) = lower(candidate)) then
    candidate := left(candidate, 31) || '-' || substr(new.id::text, 1, 8);
  end if;
  supported_team := coalesce(nullif(trim(new.raw_user_meta_data->>'team'), ''), 'Diğer');
  if supported_team not in ('Beşiktaş','Diğer','Fenerbahçe','Galatasaray','Trabzonspor') then
    supported_team := 'Diğer';
  end if;
  insert into public.profiles (id, username, team)
  values (new.id, candidate, supported_team)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.change_team_once(new_team text)
returns public.profiles
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  changed public.profiles;
begin
  if auth.uid() is null then raise exception 'Oturum gerekli.'; end if;
  if new_team not in ('Beşiktaş','Diğer','Fenerbahçe','Galatasaray','Trabzonspor') then
    raise exception 'Geçersiz takım.';
  end if;
  update public.profiles
  set team = new_team, team_changed = true, updated_at = now()
  where id = auth.uid() and team_changed = false and team <> new_team
  returning * into changed;
  if changed.id is null then raise exception 'Takım değişikliği kullanılamıyor.'; end if;
  return changed;
end;
$$;

create or replace function public.enforce_prediction_integrity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_match public.matches;
begin
  if auth.uid() is not null and new.user_id <> auth.uid() then
    raise exception 'Başka kullanıcı adına tahmin kaydedilemez.';
  end if;
  select * into target_match from public.matches where id = new.match_id;
  if target_match.id is null then raise exception 'Maç bulunamadı.'; end if;
  if target_match.status in ('iptal','ertelendi') then raise exception 'Bu maç tahmine kapalı.'; end if;
  if now() >= target_match.kickoff - interval '15 minutes' then
    raise exception 'Tahmin süresi doldu.';
  end if;
  new.submitted_at := now();
  return new;
end;
$$;

drop trigger if exists predictions_integrity_before_write on public.predictions;
create trigger predictions_integrity_before_write
before insert or update on public.predictions
for each row execute function public.enforce_prediction_integrity();

create or replace function public.get_match_prediction_consensus(p_match_id text)
returns table(total bigint, home_count bigint, draw_count bigint, away_count bigint, home_pct numeric, draw_pct numeric, away_pct numeric)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with allowed as (
    select id from public.matches
    where id = p_match_id and now() >= kickoff - interval '15 minutes'
  ), counts as (
    select
      count(*)::bigint as total,
      count(*) filter (where pick='1')::bigint as home_count,
      count(*) filter (where pick='X')::bigint as draw_count,
      count(*) filter (where pick='2')::bigint as away_count
    from public.predictions p join allowed a on a.id = p.match_id
  )
  select total, home_count, draw_count, away_count,
    round(100.0 * home_count / nullif(total,0), 1),
    round(100.0 * draw_count / nullif(total,0), 1),
    round(100.0 * away_count / nullif(total,0), 1)
  from counts;
$$;

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.match_analysis enable row level security;
alter table public.predictions enable row level security;
alter table public.results enable row level security;
alter table public.rewards enable row level security;
alter table public.league_standings enable row level security;
alter table public.weekly_stories enable row level security;
alter table public.match_lineups enable row level security;
alter table public.match_absences enable row level security;
alter table public.model_predictions enable row level security;
alter table public.match_events enable row level security;

do $$
declare p record;
begin
  for p in select schemaname, tablename, policyname from pg_policies
    where schemaname='public' and tablename = any(array[
      'profiles','matches','match_analysis','predictions','results','rewards','league_standings',
      'weekly_stories','match_lineups','match_absences','model_predictions','match_events'
    ])
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

create policy profiles_own_read on public.profiles for select to authenticated using (id = auth.uid());
create policy profiles_own_insert on public.profiles for insert to authenticated with check (id = auth.uid() and is_admin = false and team_changed = false);
create policy profiles_admin_all on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy predictions_own_read on public.predictions for select to authenticated using (user_id = auth.uid());
create policy predictions_own_insert on public.predictions for insert to authenticated with check (user_id = auth.uid());
create policy predictions_own_update on public.predictions for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy predictions_admin_all on public.predictions for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy matches_public_read on public.matches for select to anon, authenticated using (true);
create policy match_analysis_public_read on public.match_analysis for select to anon, authenticated using (true);
create policy results_public_read on public.results for select to anon, authenticated using (true);
create policy rewards_public_read on public.rewards for select to anon, authenticated using (true);
create policy standings_public_read on public.league_standings for select to anon, authenticated using (true);
create policy stories_public_read on public.weekly_stories for select to anon, authenticated using (is_published = true);
create policy lineups_public_read on public.match_lineups for select to anon, authenticated using (true);
create policy absences_public_read on public.match_absences for select to anon, authenticated using (true);
create policy model_predictions_public_read on public.model_predictions for select to anon, authenticated using (true);
create policy match_events_public_read on public.match_events for select to anon, authenticated using (verified = true);

create policy matches_admin_all on public.matches for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy match_analysis_admin_all on public.match_analysis for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy results_admin_all on public.results for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy rewards_admin_all on public.rewards for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy standings_admin_all on public.league_standings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy stories_admin_all on public.weekly_stories for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy lineups_admin_all on public.match_lineups for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy absences_admin_all on public.match_absences for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy model_predictions_admin_all on public.model_predictions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy match_events_admin_all on public.match_events for all to authenticated using (public.is_admin()) with check (public.is_admin());

revoke all on public.profiles, public.predictions from anon;
revoke update, delete on public.profiles from authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.predictions to authenticated;
grant select on public.matches, public.match_analysis, public.results, public.rewards, public.league_standings,
  public.weekly_stories, public.match_lineups, public.match_absences, public.model_predictions, public.match_events to anon, authenticated;
grant insert, update, delete on public.matches, public.match_analysis, public.results, public.rewards, public.league_standings,
  public.weekly_stories, public.match_lineups, public.match_absences, public.model_predictions, public.match_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.change_team_once(text) to authenticated;
grant execute on function public.get_match_prediction_consensus(text) to anon, authenticated;

comment on function public.get_match_prediction_consensus(text) is
  'Tahmin kilidi kapandıktan sonra yalnız anonim toplam dağılım döndürür; bireysel tahminleri açığa çıkarmaz.';

commit;
