begin;

create table if not exists public.football_weekly_player_scores (
  id bigint generated by default as identity primary key,
  league_id text not null,
  season_id text not null,
  round_id text not null,
  player_id text not null,
  algorithm_version text not null,
  status text not null check (status in ('provisional','published','failed')),
  score numeric(4,1) not null check (score between 0 and 10),
  minutes integer not null default 0 check (minutes >= 0),
  payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  computed_at timestamptz not null default now(),
  unique (league_id, season_id, round_id, player_id, algorithm_version)
);

create table if not exists public.football_weekly_awards (
  id bigint generated by default as identity primary key,
  league_id text not null,
  season_id text not null,
  round_id text not null,
  algorithm_version text not null,
  status text not null check (status in ('provisional','published','failed')),
  star_player_id text,
  formation text,
  payload jsonb not null default '{}'::jsonb,
  calculation_evidence jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  computed_at timestamptz not null default now(),
  is_stale boolean not null default false,
  unique (league_id, season_id, round_id, algorithm_version)
);

create index if not exists football_weekly_scores_round_idx
  on public.football_weekly_player_scores (league_id, season_id, round_id, score desc);
create index if not exists football_weekly_awards_published_idx
  on public.football_weekly_awards (league_id, season_id, status, computed_at desc);

alter table public.football_weekly_player_scores enable row level security;
alter table public.football_weekly_awards enable row level security;

revoke all on public.football_weekly_player_scores from anon, authenticated;
revoke all on public.football_weekly_awards from anon, authenticated;
grant select on public.football_weekly_player_scores to anon, authenticated;
grant select on public.football_weekly_awards to anon, authenticated;

drop policy if exists "published weekly scores are public" on public.football_weekly_player_scores;
create policy "published weekly scores are public"
  on public.football_weekly_player_scores for select
  to anon, authenticated
  using (status = 'published');

drop policy if exists "published weekly awards are public" on public.football_weekly_awards;
create policy "published weekly awards are public"
  on public.football_weekly_awards for select
  to anon, authenticated
  using (status = 'published');

comment on table public.football_weekly_player_scores is
  'Service-role-only XYZSkor v1 weekly player score evidence; public reads require published status.';
comment on table public.football_weekly_awards is
  'Idempotent round awards computed by XYZSkor from Sportmonks fixture, lineup and event data.';

commit;
